pipeline-definition:
  type: object

  required: [name, fastqs, steps]

  properties:

    name:
      type: string

    description:
      type: string
      minimum: 0

    resources:
      type: object
      properties:
        queue:
          type: string
        ppn:
          type: integer
          minimum: 0
        nodes:
          type: integer
          minimum: 0
        mem:
          type: string
          minimum: 0

    fastqs:
      type: object
      required: [path, pattern]
      properties:
        paired:
          type: boolean
        path:
          type: string
        pattern:
          type: string
        start-at:
          type: integer
        finish-at:
          type: integer

    references:
      type: array
      items:
        type: object
        required: [name, path]
        properties:
          name:
            type: string
          path:
            type: string

    destinations:
      type: array
      items:
        type: object
        required: [name, path]
        properties:
          name:
            type: string
          path:
            type: string

    steps:
      type: array
      items:
        type: object
        properties:
          generic:
            type: object
            required: [name, commands]
            properties:
              name:
                type: string

              outputs:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      enum:
                        - BAM
                        - regular
                    destination:
                      type: string

              commands:
                type: array
                items:
                  type: string

              precommands:
                type: array
                items:
                  type: object
                  required: [command, variable]
                  properties:
                    command:
                      type: string
                    variable:
                      type: string

              modules:
                type: array
                items:
                  type: string

